spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001

eureka:
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式;以上配置后，还需要在需要注册到eureka中的服务中进行配置心跳时间、和宕机时间,之后，1秒清理时候会判断是否宕机（猜测服务会给出标识），宕机就清理
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@localhost:7001/eureka
  instance: #eureka实例
    hostname: localhost #实例所在的主机名称

spring:
  security:
    user:
      name: admin
      password: admin
  profiles: dev
  application:
    name: microcloud-config-eureka-client
---
server:
  port: 7002

eureka:
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式;以上配置后，还需要在需要注册到eureka中的服务中进行配置心跳时间、和宕机时间,之后，1秒清理时候会判断是否宕机（猜测服务会给出标识），宕机就清理
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@localhost:7002/eureka
  instance: #eureka实例
    hostname: localhost #实例所在的主机名称

spring:
  security:
    user:
      name: admin
      password: admin
  profiles: beta
  application:
    name: microcloud-config-eureka-client
